{% set version = "2.10.0" %}

package:
  name: arb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fredrik-johansson/arb/archive/{{ version }}.tar.gz
  sha256: 5315549eb2af112a12750f8967282b0150ffa62750d4e3c3ea0ac5ad75da8c4b

build:
  number: 0
  skip: true        # [win]

requirements:
  build:
    - toolchain
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint
  run:
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint

test:
  commands:
    - test -f $PREFIX/include/arb.h
    - test -f $PREFIX/lib/libarb.a
    - test -f $PREFIX/lib/libarb.so         # [linux]
    - test -f $PREFIX/lib/libarb.dylib      # [osx]

about:
  home: http://arblib.org
  license: GPL v2+
  license_file: LICENSE
  summary: 'A C library for arbitrary-precision interval arithmetic'

extra:
  recipe-maintainers:
    - isuruf
