{% set version = "2.12.0" %}

package:
  name: arb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fredrik-johansson/arb/archive/{{ version }}.tar.gz
  sha256: 346af6a69118ebc6535c24b1d31055d315bab026dd24059c262a5fbcfaec6748

build:
  number: 0
  skip: true        # [win]
  run_exports:
    - {{ pin_subpackage('arb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gmp
    - mpfr
    - libflint
  run:
    - gmp
    - mpfr
    - libflint

test:
  commands:
    - test -f $PREFIX/include/arb.h
    - test -f $PREFIX/lib/libarb.a
    - test -f $PREFIX/lib/libarb.so         # [linux]
    - test -f $PREFIX/lib/libarb.dylib      # [osx]

about:
  home: http://arblib.org
  license: GPL v2+
  license_file: LICENSE
  summary: 'A C library for arbitrary-precision interval arithmetic'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
