{% set version = "2.22.1" %}

package:
  name: arb
  version: {{ version }}

source:
  url: https://github.com/fredrik-johansson/arb/archive/{{ version }}.tar.gz
  sha256: 1ef85518eee04885e8a90196498bc75e4e2410621d4184f2bc01d46b7080a243

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('arb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make      # [unix]
    - cmake     # [win]
    - ninja     # [win]
  host:
    - gmp       # [unix]
    - mpir      # [win]
    - mpfr
    - libflint
    - pthreads-win32    # [win]
  run:
    - pthreads-win32    # [win]

test:
  commands:
    - test -f $PREFIX/include/arb.h                     # [unix]
    - if not exist %LIBRARY_INC%\arb.h exit 1           # [win]
    - if not exist %LIBRARY_LIB%\arb.lib exit 1         # [win]
    - if not exist %LIBRARY_BIN%\arb-2.dll exit 1         # [win]
    - test -f $PREFIX/lib/libarb.so         # [linux]
    - test -f $PREFIX/lib/libarb.dylib      # [osx]

about:
  home: http://arblib.org
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A C library for arbitrary-precision interval arithmetic

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
