{% set version = "2.16.0" %}

package:
  name: arb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fredrik-johansson/arb/archive/{{ version }}.tar.gz
  sha256: 77464be4d34a511bb004457f862fec857ff934b0ed58d56d6f52d76ebadd4daf

build:
  number: 1001
  skip: true        # [win]
  run_exports:
    - {{ pin_subpackage('arb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - gmp
    - mpfr
    - libflint
  run:
    - gmp
    - mpfr
    - libflint
test:
  commands:
    - test -f $PREFIX/include/arb.h
    - test -f $PREFIX/lib/libarb.a
    - test -f $PREFIX/lib/libarb.so         # [linux]
    - test -f $PREFIX/lib/libarb.dylib      # [osx]

about:
  home: http://arblib.org
  license: GPL v2+
  license_file: LICENSE
  summary: 'A C library for arbitrary-precision interval arithmetic'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
