{% set version = "2.13.0" %}

package:
  name: arb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/fredrik-johansson/arb/archive/{{ version }}.tar.gz
  sha256: d075116d094bfda96f9c4ce10bb9bf23b333a8246f48c532427168d0f91b7788
  patches:
    # https://github.com/fredrik-johansson/arb/issues/209
    - 1288a174e31e2efd550f62351036c499ed72c61c.patch

build:
  number: 1
  skip: true        # [win]

requirements:
  build:
    - toolchain
    - gmp >=5.0.1,<7
    - mpfr 4.*
    - libflint 2.5.*
  run:
    - gmp >=5.0.1,<7
    - mpfr 4.*
    - libflint 2.5.*

test:
  commands:
    - test -f $PREFIX/include/arb.h
    - test -f $PREFIX/lib/libarb.a
    - test -f $PREFIX/lib/libarb.so         # [linux]
    - test -f $PREFIX/lib/libarb.dylib      # [osx]

about:
  home: http://arblib.org
  license: GPL v2+
  license_file: LICENSE
  summary: 'A C library for arbitrary-precision interval arithmetic'

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
