travis:
  secure:
    BINSTAR_TOKEN: b7ke8SjzmdThmoQ75Lvpb4cetQZymU4Sn6h6x3gmNANnFY3anRh22t9NbNscVQV+vpTlrTnHYue3KPjLnFJ+xlMr8MDcZq5XxZCaNBkUFHXi7MYwZog9CnGdgRQOAzSNGq2UxfyR8/Eq/pKtmHZVxN3fcWGpIUepF8jJlpcnh4G0ztMwlrnxD9p0i0vfr5dlPLI5r2ZpW4WKvYRYJX6VGsqSmJIwhLvVuLmClWPOMCNDWBu7G6/eA5u+Ju3oIkHyKdf1oj1OWAccavQrY3VS3PS63K9g/g/TcLyWoQP2jotZwp537OdZYv7/HkNFA/lrsx8H4n6d1o3soeawAwZ3TOWucw5LFooUYOTkf5NX/io3E2r9co1b85V6aIQaL7tOA/+5wN7jPfd+3hVY5NiP3yEPCQEId5X+npK3iJDo+P+gISo9CCmciY1Dtrm+izy5a2cdASWHYru56He/Q8K+kr/g4l8FUis+BjxngXaq64TAJivWUv4pSkFsby4fo2k81ldd6k1oDiJKeydB+naaBh0latEvuyttGdRigmMi4NcFkh+h1IKfsTsy8zk2Xa1Nk5AQ7ROFZU2oV+iV4hhnkkZsWrEylnqcgLuS5sj2dzt9XSbTc0Au8ghOaTW8vddGwed98YI+w+gXVlS2RNnMK3x0SQQmGSuqdo0w75ntkUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
