appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: fv0IEZqlqdl8cF3XXaGmdxnpFzT/Xi+AbPnbYY3qQDdvXbjZKnx7zTTETBKiP7NzpDzexjXh6rJFpVegX7yLatf/qQ3vSf4H3nV/xiLA/ad2cWeJh8uWZ51s/306iSSLzUeLOCNJx/fZvgO3bouFwjdWwq2yUJsARYnJ3Mr9C9FbzJzqj6sAPI0i+A7Vo875m5J3ujS4vlrQpbs+dtEJCPiSNLY7twQtNG+FHIA6a6XDBhleRGa782Djvh6rgitSkebm7FKwMCElOlGIcm+t29GTBNV+X/SFeu2MdI9zxWLCl9ibcCDRPQ+i83a0+3FS8RFb0r9F/BHrYGO1apAIdcDxkSVwCbgJKJhgS7Wiyd9Dr9ODCWCz7qacX2OH80NPR9KPXLezV6N2d2biaOr2/1Vgnj21UG5+tOLWwsf5Xhvl58fARR0o/nkFO7DcIHsLMN7FGSCbNtVlTEbJKf3IOlvtL+C0/iGJZbSEnxHwbG+2siZtlmKlvEznC3I+52WcP8tNiVR9zwvMkozMHMGT2UJhEziuVO+RDBWQGP54A4esI7t/ZDmhmp1BduxNKuJYgqsC6EJtcNbuoi4tMI8za1BnPV3PI6DfUigCkued7Qz4I1zCS6UdKT2NrSqiX7T9uwG4IijHZuTItlloMZRqlVyeXUehocTylKpy+HsSYRk=}
conda_forge_output_validation: true
